<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
session_cache_expire(30);
session_start();
date_default_timezone_set("America/New_York");

if (!isset($_SESSION['access_level']) || $_SESSION['access_level'] < 2) {
    header('Location: login.php');
    die();
}

require_once('database/dbPersons.php');
require_once('database/dbEvents.php');
require_once('database/dbpersonhours.php');

$format = $_POST['format'] ?? 'csv';
$admin = $_POST['admin'] ?? $_SESSION['_id'] ?? 'Unknown';
$generatedTime = $_POST['time'] ?? date("d-M-Y H:i:s e");

$reportData = calcTop10();
$time = time();

// PDF VIEW
if ($format === 'pdf') {
    ?>
    <!DOCTYPE html>
    <html lang="en">
    <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Top 10 Volunteers Report | Love Thy Neighbor Community Food Pantry</title>
    <link href="css/base.css" rel="stylesheet">
    <link href="css/report.css" rel="stylesheet">
</head>
    <body>

        <div class="report-page">
            <div class="report-header">
                <h1>Top Ten Volunteers Report</h1>
                <h2>Love Thy Neighbor Community Food Pantry</h2>
            </div>

            <div class="report-meta">
                <strong>Generated by:</strong> <?php echo htmlspecialchars($admin); ?><br>
                <strong>Date generated:</strong> <?php echo htmlspecialchars($generatedTime); ?><br>
                <strong>Definition:</strong> Top ten volunteers by total recorded hours
            </div>

            <div class="report-summary">
                <strong>Total volunteers shown:</strong> <?php echo count($reportData); ?>
            </div>

            <?php if (!empty($reportData)): ?>
                <table class="report-table">
                    <thead>
                        <tr>
                            <th style="width: 15%;">Rank</th>
                            <th style="width: 30%;">First Name</th>
                            <th style="width: 30%;">Last Name</th>
                            <th style="width: 12.5%;">Hours</th>
                            <th style="width: 12.5%;">Minutes</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $rank = 1; ?>
                        <?php foreach ($reportData as $p): ?>
                            <tr>
                                <td><?php echo $rank++; ?></td>
                                <td><?php echo htmlspecialchars($p[0] ?? ''); ?></td>
                                <td><?php echo htmlspecialchars($p[1] ?? ''); ?></td>
                                <td><?php echo (int)($p[2] ?? 0); ?></td>
                                <td><?php echo (int)($p[3] ?? 0); ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            <?php else: ?>
                <div class="no-results">
                    No volunteer data was found.
                </div>
            <?php endif; ?>
        </div>

        <div class="actions">
            <a href="topVolunteerReport.php">Back to Report Options</a>
            <a href="index.php">Return to Dashboard</a>
        </div>

    </body>
    </html>
    <?php
    exit();
}

// CSV EXPORT
if ($format === 'csv') {
    header("Content-Type: text/csv");
    header("Content-Disposition: attachment; filename=top10_report_{$time}.csv");
    header("Pragma: no-cache");
    header("Expires: 0");

    $output = fopen('php://output', 'w');
    fputcsv($output, ["top10_report_{$time}.csv"]);

    fputcsv($output, ["First Name", "Last Name", "Hours", "Minutes"]);

    foreach ($reportData as $p) {
        fputcsv($output, [
            $p[0],
            $p[1],
            $p[2],
            $p[3]
        ]);
    }
    fclose($output);
    exit();
}

// EXCEL EXPORT
header("Content-Type: application/vnd.ms-excel");
header("Content-Disposition: attachment; filename=top10_report_{$time}.xls");
header("Pragma: no-cache");
header("Expires: 0");

echo "<html><head><meta charset='UTF-8'></head><body>";
echo "<table border='1' style='border-collapse: collapse; font-family: Arial, sans-serif; text-align: center;'>";

echo "<tr><th colspan='4' style='font-size: 18px; background-color: #004488; color: white; padding: 10px;'>Top Ten Volunteers Report</th></tr>";

echo "<tr>
        <th style='background-color: #88CCEE; padding: 5px;'>First Name</th>
        <th style='background-color: #AA4499; padding: 5px;'>Last Name</th>
        <th style='background-color: #DDCC77; padding: 5px;'>Hours</th>
        <th style='background-color: #88CCEE; padding: 5px;'>Minutes</th>
      </tr>";

foreach ($reportData as $p) {
    echo "<tr>
            <td style='background-color: #EAEAEA; padding: 5px; text-align: center;'>" . htmlspecialchars($p[0] ?? '') . "</td>
            <td style='padding: 5px;'>" . htmlspecialchars($p[1] ?? '') . "</td>
            <td style='padding: 5px;'>" . (int)($p[2] ?? 0) . "</td>
            <td style='padding: 5px;'>" . (int)($p[3] ?? 0) . "</td>
          </tr>";
}

echo "</table>";
echo "</body></html>";
exit();
?>