<?php
session_cache_expire(30);
session_start();
ini_set("display_errors", 1);
error_reporting(E_ALL);
date_default_timezone_set("America/New_York");

// Ensure admin authentication
if (!isset($_SESSION['access_level']) || $_SESSION['access_level'] < 2) {
    header('Location: login.php');
    die();
}

require_once('database/reports.php');

$admin = $_POST['admin'] ?? $_SESSION['_id'] ?? 'Unknown';
$generatedTime = $_POST['time'] ?? date("d-M-Y H:i:s e");

$inactiveVolunteers = getInactiveVolunteers();
$totalInactive = count($inactiveVolunteers);
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inactive Volunteers Report | Love Thy Neighbor Community Food Pantry</title>
    <link href="css/base.css" rel="stylesheet">
    <link href="css/report.css" rel="stylesheet">
</head>
<body>

    <div class="report-page">
        <div class="report-header">
            <h1>Inactive Volunteers Report</h1>
            <h2>Love Thy Neighbor Community Food Pantry</h2>
        </div>

        <div class="report-meta">
            <strong>Generated by:</strong> <?php echo htmlspecialchars($admin); ?><br>
            <strong>Date generated:</strong> <?php echo htmlspecialchars($generatedTime); ?><br>
            <strong>Definition:</strong> Volunteers with no recorded participation in the past year
        </div>

        <div class="report-summary">
            <strong>Total inactive volunteers:</strong> <?php echo $totalInactive; ?>
        </div>

        <?php if ($totalInactive > 0): ?>
            <table class="report-table">
                <thead>
                    <tr>
                        <th style="width: 20%;">User ID</th>
                        <th style="width: 30%;">First Name</th>
                        <th style="width: 30%;">Last Name</th>
                        <th style="width: 40%;">Last Participation Date</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($inactiveVolunteers as $volunteer): ?>
                        <tr>
                            <td><?php echo htmlspecialchars($volunteer[0]); ?></td>
                            <td><?php echo htmlspecialchars($volunteer[1] ?? ''); ?></td>
                            <td><?php echo htmlspecialchars($volunteer[2] ?? ''); ?></td>
                            <td>
                                <?php
                                    echo !empty($volunteer[3])
                                        ? htmlspecialchars($volunteer[3])
                                        : 'No participation on record';
                                ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php else: ?>
            <div class="no-results">
                No inactive volunteers were found.
            </div>
        <?php endif; ?>
    </div>

    <div class="actions">
        <a href="inactiveVolunteersReport.php">Back to Report Options</a>
        <a href="index.php">Return to Dashboard</a>
    </div>

</body>
</html>
