<?php
session_cache_expire(30);
session_start();
ini_set("display_errors", 1);
error_reporting(E_ALL);
date_default_timezone_set("America/New_York");

// Ensure admin authentication
if (!isset($_SESSION['access_level']) || $_SESSION['access_level'] < 2) {
    header('Location: login.php');
    die();
}

require_once('database/reports.php');

$admin = $_POST['admin'] ?? $_SESSION['_id'] ?? 'Unknown';
$generatedTime = $_POST['time'] ?? date("d-M-Y H:i:s e");

$sdate = $_POST['sdate'] ?? '';
$edate = $_POST['edate'] ?? '';
$selectedRoles = $_POST['roles'] ?? [];

$roleSummary = [];
$totalMinutes = 0;

// Convert selected role values to ints
$roleIds = array_map('intval', $selectedRoles);

if (!empty($sdate) && !empty($edate) && !empty($roleIds)) {
    $startDateTime = $sdate . " 00:00:00";
    $endDateTime = date("Y-m-d H:i:s", strtotime($edate . " +1 day"));

    $roleSummary = hoursPerRoleWithDateRange($roleIds, $startDateTime, $endDateTime);

    foreach ($roleSummary as $row) {
        $hours = (int)($row[1] ?? 0);
        $minutes = (int)($row[2] ?? 0);
        $totalMinutes += ($hours * 60) + $minutes;
    }
}

$totalHoursOverall = intdiv($totalMinutes, 60);
$totalRemainingMinutes = $totalMinutes % 60;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hour Category Report | Love Thy Neighbor Community Food Pantry</title>
    <link href="css/base.css" rel="stylesheet">
    <link href="css/report.css" rel="stylesheet">
</head>
<body>

    <div class="report-page">
        <div class="report-header">
            <h1>Hour Category Report</h1>
            <h2>Love Thy Neighbor Community Food Pantry</h2>
        </div>

        <div class="report-meta">
            <strong>Generated by:</strong> <?php echo htmlspecialchars($admin); ?><br>
            <strong>Date generated:</strong> <?php echo htmlspecialchars($generatedTime); ?><br>
            <strong>Selected start date(yyyy-mm-dd):</strong> <?php echo htmlspecialchars($sdate); ?><br>
            <strong>Selected end date(yyyy-mm-dd):</strong> <?php echo htmlspecialchars($edate); ?>
        </div>

        <?php if (!empty($sdate) && !empty($edate) && !empty($roleIds) && !empty($roleSummary)): ?>
            <div class="report-summary">
                <strong>Selected categories:</strong> <?php echo count($roleIds); ?><br>
                <strong>Total categorized time:</strong><b> <?php echo $totalHoursOverall; ?> hours, <?php echo $totalRemainingMinutes; ?> minutes</b>
            </div>

            <table class="report-table">
                <thead>
                    <tr>
                        <th style="width: 50%;">Hour Category</th>
                        <th style="width: 25%;">Hours</th>
                        <th style="width: 25%;">Minutes</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($roleSummary as $row): ?>
                        <tr>
                            <td><?php echo htmlspecialchars($row[0] ?? ''); ?></td>
                            <td><?php echo (int)($row[1] ?? 0); ?></td>
                            <td><?php echo (int)($row[2] ?? 0); ?></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php else: ?>
            <div class="no-results">
                No hour category data was found for the selected date range and role selection.
            </div>
        <?php endif; ?>
    </div>

    <div class="actions">
        <a href="hourCategoryReport.php">Back to Report Options</a>
        <a href="index.php">Return to Dashboard</a>
    </div>

</body>
</html>