<?php
session_cache_expire(30);
session_start();
ini_set("display_errors", 1);
error_reporting(E_ALL);
date_default_timezone_set("America/New_York");

// Ensure admin authentication
if (!isset($_SESSION['access_level']) || $_SESSION['access_level'] < 2) {
    header('Location: login.php');
    die();
}

require_once('database/reports.php');

$admin = $_POST['admin'] ?? $_SESSION['_id'] ?? 'Unknown';
$generatedTime = $_POST['time'] ?? date("d-M-Y H:i:s e");

$sdate = $_POST['sdate'] ?? '';
$edate = $_POST['edate'] ?? '';

$totalHours = [0, 0];
$totalUnique = 0;

if (!empty($sdate) && !empty($edate)) {
    $startDateTime = $sdate . " 00:00:00";
    $endDateTime = date("Y-m-d H:i:s", strtotime($edate . " +1 day"));

    $totalHours = totalHoursForDateRange($startDateTime, $endDateTime);
    $totalUnique = countUniqueVolunteersForDateRange($startDateTime, $endDateTime);
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Total Hours Report | Love Thy Neighbor Community Food Pantry</title>
    <link href="css/base.css" rel="stylesheet">
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            color: #000;
            background: #fff;
            margin: 0;
            padding: 0;
        }

        .report-page {
            width: 8.5in;
            min-height: 11in;
            margin: 0 auto;
            padding: 0.6in;
            box-sizing: border-box;
            background: #fff;
        }

        .report-header {
            text-align: center;
            margin-bottom: 0.3in;
        }

        .report-header h1 {
            margin: 0 0 0.1in 0;
            font-size: 24px;
        }

        .report-header h2 {
            margin: 0;
            font-size: 16px;
            font-weight: normal;
        }

        .report-meta {
            margin-bottom: 0.3in;
            font-size: 14px;
            line-height: 1.5;
        }

        .report-summary {
            margin-bottom: 0.25in;
            font-size: 14px;
            line-height: 1.8;
        }

        .summary-box {
            margin-top: 0.3in;
            border: 1px solid #000;
            padding: 16px;
            font-size: 15px;
            line-height: 1.8;
        }

        .no-results {
            margin-top: 0.3in;
            padding: 12px;
            border: 1px solid #000;
            font-size: 14px;
        }

        .actions {
            width: 8.5in;
            margin: 1rem auto 2rem auto;
            text-align: center;
        }

        .actions a {
            display: inline-block;
            text-decoration: none;
            padding: 10px 18px;
            border: 1px solid #000;
            color: #000;
            background: #f5f5f5;
            margin: 0 8px;
        }

        @media print {
            .actions {
                display: none;
            }

            .report-page {
                margin: 0;
                box-shadow: none;
            }
        }
    </style>
</head>
<body>

    <div class="report-page">
        <div class="report-header">
            <h1>Total Hours Report</h1>
            <h2>Love Thy Neighbor Community Food Pantry</h2>
        </div>

        <div class="report-meta">
            <strong>Generated by:</strong> <?php echo htmlspecialchars($admin); ?><br>
            <strong>Date generated:</strong> <?php echo htmlspecialchars($generatedTime); ?><br>
            <strong>Selected start date(yyyy-mm-dd):</strong> <?php echo htmlspecialchars($sdate); ?><br>
            <strong>Selected end date(yyyy-mm-dd):</strong> <?php echo htmlspecialchars($edate); ?>
        </div>

        <?php if (!empty($sdate) && !empty($edate)): ?>
            <div class="report-summary">
                <strong>Report contents:</strong> Total volunteer time and unique volunteer count for the selected date range.
            </div>

            <div class="summary-box">
                <strong>Total volunteered time:</strong>
                <?php echo (int)$totalHours[0]; ?> hours, <?php echo (int)$totalHours[1]; ?> minutes
                <br>

                <strong>Unique volunteers:</strong>
                <?php echo (int)$totalUnique; ?>
            </div>
        <?php else: ?>
            <div class="no-results">
                No report data could be generated because the date range was not provided.
            </div>
        <?php endif; ?>
    </div>

    <div class="actions">
        <a href="totalHoursReport.php">Back to Report Options</a>
        <a href="index.php">Return to Dashboard</a>
    </div>

</body>
</html>
