<?php
session_cache_expire(30);
session_start();
ini_set("display_errors", 1);
error_reporting(E_ALL);
date_default_timezone_set("America/New_York");

// Ensure admin authentication
if (!isset($_SESSION['access_level']) || $_SESSION['access_level'] < 2) {
    header('Location: login.php');
    die();
}

require_once('database/reports.php');

$admin = $_POST['admin'] ?? $_SESSION['_id'] ?? 'Unknown';
$generatedTime = $_POST['time'] ?? date("d-M-Y H:i:s e");

$sdate = $_POST['sdate'] ?? '';
$edate = $_POST['edate'] ?? '';

$volunteers = [];
$totalUnique = 0;

if (!empty($sdate) && !empty($edate)) {
    $startDateTime = $sdate . " 00:00:00";
    $endDateTime = date("Y-m-d H:i:s", strtotime($edate . " +1 day"));

    $volunteers = volunteerUniqueEventsForDateRange($startDateTime, $endDateTime);
    $totalUnique = is_array($volunteers) ? count($volunteers) : 0;
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Unique Volunteer Report | Love Thy Neighbor Community Food Pantry</title>
    <link href="css/base.css" rel="stylesheet">
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            color: #000;
            background: #fff;
            margin: 0;
            padding: 0;
        }

        .report-page {
            width: 8.5in;
            min-height: 11in;
            margin: 0 auto;
            padding: 0.6in;
            box-sizing: border-box;
            background: #fff;
        }

        .report-header {
            text-align: center;
            margin-bottom: 0.3in;
        }

        .report-header h1 {
            margin: 0 0 0.1in 0;
            font-size: 24px;
        }

        .report-header h2 {
            margin: 0;
            font-size: 16px;
            font-weight: normal;
        }

        .report-meta {
            margin-bottom: 0.3in;
            font-size: 14px;
            line-height: 1.5;
        }

        .report-summary {
            margin-bottom: 0.25in;
            font-size: 14px;
        }

        table.report-table {
            width: 100%;
            border-collapse: collapse;
            font-size: 14px;
        }

        table.report-table th,
        table.report-table td {
            border: 1px solid #000;
            padding: 8px 10px;
            text-align: left;
            vertical-align: top;
        }

        table.report-table th {
            background-color: #f2f2f2;
        }

        .report-footnote {
            margin-top: 0.3in;
            font-size: 13px;
        }

        .no-results {
            margin-top: 0.3in;
            padding: 12px;
            border: 1px solid #000;
            font-size: 14px;
        }

        .actions {
            width: 8.5in;
            margin: 1rem auto 2rem auto;
            text-align: center;
        }

        .actions a {
            display: inline-block;
            text-decoration: none;
            padding: 10px 18px;
            border: 1px solid #000;
            color: #000;
            background: #f5f5f5;
            margin: 0 8px;
        }

        @media print {
            .actions {
                display: none;
            }

            .report-page {
                margin: 0;
                box-shadow: none;
            }
        }
    </style>
</head>
<body>

    <div class="report-page">
        <div class="report-header">
            <h1>Unique Volunteer Report</h1>
            <h2>Love Thy Neighbor Community Food Pantry</h2>
        </div>

        <div class="report-meta">
            <strong>Generated by:</strong> <?php echo htmlspecialchars($admin); ?><br>
            <strong>Date generated:</strong> <?php echo htmlspecialchars($generatedTime); ?><br>
            <strong>Selected start date:</strong> <?php echo htmlspecialchars($sdate); ?><br>
            <strong>Selected end date:</strong> <?php echo htmlspecialchars($edate); ?>
        </div>

        <div class="report-summary">
            <strong>Total unique volunteers:</strong> <?php echo (int)$totalUnique; ?><br>
            <br>
            <i>* indicates participation before May 1 2026. All events before then count as one combined event.</i>
        </div>
        

        <?php if ($totalUnique > 0): ?>
            <table class="report-table">
                <thead>
                    <tr>
                        <th style="width: 20%;">User ID</th>
                        <th style="width: 25%;">First Name</th>
                        <th style="width: 25%;">Last Name</th>
                        <th style="width: 30%;">Event Count</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($volunteers as $volunteer): ?>
                        <tr>
                            <td><?php echo htmlspecialchars($volunteer[0] ?? ''); ?></td>
                            <td><?php echo htmlspecialchars($volunteer[1] ?? ''); ?></td>
                            <td><?php echo htmlspecialchars($volunteer[2] ?? ''); ?></td>
                            <td>
                                <?php
                                    $eventCount = (int)($volunteer[3] ?? 0);
                                    $hasPreMayFlag = !empty($volunteer[4]);

                                    echo htmlspecialchars((string)$eventCount);
                                    if ($hasPreMayFlag) {
                                        echo '*';
                                    }
                                ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>

            
        <?php else: ?>
            <div class="no-results">
                No volunteers were found for the selected date range.
            </div>
        <?php endif; ?>
    </div>

    <div class="actions">
        <a href="uniqueVolunteerReport.php">Back to Report Options</a>
        <a href="index.php">Return to Dashboard</a>
    </div>

</body>
</html>