<?php
session_cache_expire(30);
session_start();
ini_set("display_errors", 1);
error_reporting(E_ALL);
date_default_timezone_set("America/New_York");

// Ensure admin authentication
if (!isset($_SESSION['access_level']) || $_SESSION['access_level'] < 2) {
    header('Location: login.php');
    die();
}

require_once('database/reports.php');

$admin = $_POST['admin'] ?? $_SESSION['_id'] ?? 'Unknown';
$generatedTime = $_POST['time'] ?? date("d-M-Y H:i:s e");

$sdate = $_POST['sdate'] ?? '';
$edate = $_POST['edate'] ?? '';

$totalHours = [0, 0];
$totalUnique = 0;

if (!empty($sdate) && !empty($edate)) {
    $startDateTime = $sdate . " 00:00:00";
    $endDateTime = date("Y-m-d H:i:s", strtotime($edate . " +1 day"));

    $totalHours = totalHoursForDateRange($startDateTime, $endDateTime);
    $totalUnique = countUniqueVolunteersForDateRange($startDateTime, $endDateTime);
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Total Hours Report | Love Thy Neighbor Community Food Pantry</title>
    <link href="css/base.css" rel="stylesheet">
    <link href="css/report.css" rel="stylesheet">
</head>
<body>

    <div class="report-page">
        <div class="report-header">
            <h1>Total Hours Report</h1>
            <h2>Love Thy Neighbor Community Food Pantry</h2>
        </div>

        <div class="report-meta">
            <strong>Generated by:</strong> <?php echo htmlspecialchars($admin); ?><br>
            <strong>Date generated:</strong> <?php echo htmlspecialchars($generatedTime); ?><br>
            <strong>Selected start date(yyyy-mm-dd):</strong> <?php echo htmlspecialchars($sdate); ?><br>
            <strong>Selected end date(yyyy-mm-dd):</strong> <?php echo htmlspecialchars($edate); ?>
        </div>

        <?php if (!empty($sdate) && !empty($edate)): ?>
            <div class="report-summary">
                <strong>Report contents:</strong> Total volunteer time and unique volunteer count for the selected date range.
            </div>

            <div class="summary-box">
                <strong>Total volunteered time:</strong>
                <?php echo (int)$totalHours[0]; ?> hours, <?php echo (int)$totalHours[1]; ?> minutes
                <br>

                <strong>Unique volunteers:</strong>
                <?php echo (int)$totalUnique; ?>
            </div>
        <?php else: ?>
            <div class="no-results">
                No report data could be generated because the date range was not provided.
            </div>
        <?php endif; ?>
    </div>

    <div class="actions">
        <a href="totalHoursReport.php">Back to Report Options</a>
        <a href="index.php">Return to Dashboard</a>
    </div>

</body>
</html>
